# Generated by Django 5.0.2 on 2024-03-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_customer_user_alter_product_discount_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
